<?xml version="1.0" encoding="utf-8"?><Database Name="Hotelmanagment" EntityNamespace="Hotel_Managment" ContextNamespace="Hotel_Managment" Class="hotelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Hotelmanagment;Integrated Security=True" SettingsObjectName="Hotel_Managment.Properties.Settings" SettingsPropertyName="HotelmanagmentConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CreditCards" Member="CreditCards">
    <Type Name="CreditCard">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardNum" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Pin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_CreditCard" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PremissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_CreditCard" Member="CreditCards" ThisKey="Id" OtherKey="UserId" Type="CreditCard" />
      <Association Name="User_Reservation" Member="Reservations" ThisKey="Id" OtherKey="UserId" Type="Reservation" />
      <Association Name="Premission_User" Member="Premission" ThisKey="PremissionId" OtherKey="Id" Type="Premission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Foods" Member="Foods">
    <Type Name="Food">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Food_OrderFood" Member="OrderFoods" ThisKey="Id" OtherKey="FoodId" Type="OrderFood" />
    </Type>
  </Table>
  <Table Name="dbo.OrderFoods" Member="OrderFoods">
    <Type Name="OrderFood">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FoodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Food_OrderFood" Member="Food" ThisKey="FoodId" OtherKey="Id" Type="Food" IsForeignKey="true" />
      <Association Name="Room_OrderFood" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderServices" Member="OrderServices">
    <Type Name="OrderService">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SOrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_OrderService" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" />
      <Association Name="Service_OrderService" Member="Service" ThisKey="ServiceId" OtherKey="Id" Type="Service" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Premissions" Member="Premissions">
    <Type Name="Premission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PremissionName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Premission_User" Member="Users" ThisKey="Id" OtherKey="PremissionId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Reservation" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Room_Reservation" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Size" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="available" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PriceD" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Room_OrderFood" Member="OrderFoods" ThisKey="Id" OtherKey="RoomId" Type="OrderFood" />
      <Association Name="Room_OrderService" Member="OrderServices" ThisKey="Id" OtherKey="RoomId" Type="OrderService" />
      <Association Name="Room_Reservation" Member="Reservations" ThisKey="Id" OtherKey="RoomId" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="Services">
    <Type Name="Service">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeService" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Service_OrderService" Member="OrderServices" ThisKey="Id" OtherKey="ServiceId" Type="OrderService" />
    </Type>
  </Table>
</Database>